/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea1programacion;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonatan
 */
public class FrameDoctor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameDoctor.class.getName());

    /**
     * Creates new form FrameDoctor
     */
    public FrameDoctor() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombredoctor = new javax.swing.JTextField();
        txttelefonodoctor = new javax.swing.JTextField();
        txtespecialidad = new javax.swing.JTextField();
        botoncapturar = new javax.swing.JToggleButton();
        labelcodigo = new javax.swing.JLabel();
        labelnombredoctor = new javax.swing.JLabel();
        labeltelefonodoctor = new javax.swing.JLabel();
        labelespecialidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Doctores");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre Doctor");

        jLabel4.setText("Telefono Doctor");

        jLabel5.setText("Especialidad");

        txtcodigo.addActionListener(this::txtcodigoActionPerformed);
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoKeyPressed(evt);
            }
        });

        txtnombredoctor.addActionListener(this::txtnombredoctorActionPerformed);
        txtnombredoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombredoctorKeyPressed(evt);
            }
        });

        txttelefonodoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonodoctorKeyPressed(evt);
            }
        });

        txtespecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtespecialidadKeyPressed(evt);
            }
        });

        botoncapturar.setText("Capturar Datos");
        botoncapturar.addActionListener(this::botoncapturarActionPerformed);
        botoncapturar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botoncapturarKeyPressed(evt);
            }
        });

        labelcodigo.setText("jLabel6");

        labelnombredoctor.setText("jLabel7");

        labeltelefonodoctor.setText("jLabel8");

        labelespecialidad.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labeltelefonodoctor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botoncapturar)
                                        .addGap(54, 54, 54)
                                        .addComponent(labelcodigo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelnombredoctor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelespecialidad, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtespecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txttelefonodoctor)
                                    .addComponent(txtnombredoctor)
                                    .addComponent(txtcodigo))))))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombredoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttelefonodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botoncapturar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelcodigo)
                        .addComponent(labelnombredoctor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltelefonodoctor)
                    .addComponent(labelespecialidad))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncapturarActionPerformed
        // TODO add your handling code here:
        botoncapturar();
    }//GEN-LAST:event_botoncapturarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtnombredoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombredoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombredoctorActionPerformed

    private void txtcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txtnombredoctor.requestFocus(); 
        }
    }//GEN-LAST:event_txtcodigoKeyPressed

    private void txtnombredoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombredoctorKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txttelefonodoctor.requestFocus(); 
        }
    }//GEN-LAST:event_txtnombredoctorKeyPressed

    private void txttelefonodoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonodoctorKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txtespecialidad.requestFocus(); 
        }
    }//GEN-LAST:event_txttelefonodoctorKeyPressed

    private void txtespecialidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtespecialidadKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        botoncapturar.requestFocus(); 
        }
    }//GEN-LAST:event_txtespecialidadKeyPressed

    private void botoncapturarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoncapturarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         botoncapturar();
         }
    }//GEN-LAST:event_botoncapturarKeyPressed

    public void botoncapturar(){
            // TODO add your handling code here:
    Integer codigo;
    String nombredoctor;
    String telefonodoctor;
    String especialidad;
    codigo=Integer.parseInt(txtcodigo.getText());
    nombredoctor=txtnombredoctor.getText();
    telefonodoctor=txttelefonodoctor.getText();
    especialidad=txtespecialidad.getText();
    //++++++++++++++++++SE instancia la calse++++++++++++++
    
    Doctor doctor=new Doctor();
    //       Enviando Valores a la clase+++++++++++++++++++
    doctor.codigo=codigo;
    doctor.nombredoctor=nombredoctor;
    doctor.telefonodoctor=telefonodoctor;
    doctor.especialidad=especialidad;
    
    
    //+++++++++++++Impresion de resultados+++++++++++++++++
    
    labelcodigo.setText(doctor.codigo+"");
    labelnombredoctor.setText(doctor.nombredoctor);
    labeltelefonodoctor.setText(doctor.telefonodoctor);
    labelespecialidad.setText(doctor.especialidad);
    limpiar();
    JOptionPane.showMessageDialog(null, "Registro Ingresado");
}
    public void limpiar(){
    txtcodigo.setText("");
    txtnombredoctor.setText("");
    txttelefonodoctor.setText("");
    txtespecialidad.setText("");
    txtcodigo.requestFocus();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameDoctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botoncapturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelespecialidad;
    private javax.swing.JLabel labelnombredoctor;
    private javax.swing.JLabel labeltelefonodoctor;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtespecialidad;
    private javax.swing.JTextField txtnombredoctor;
    private javax.swing.JTextField txttelefonodoctor;
    // End of variables declaration//GEN-END:variables
}
